### PR TITLE
Add compatibility for Rails 6

### PR DESCRIPTION
**Pull request by lazyatom**
This builds on top of #11 but adds builds against ActiveRecord `~> 6.0.0`, and adjusts the gem spec to make this build possible.

### CODE REVIEW

**Comment by gtd** [comment]
rebase?

**Comment by lazyatom** [comment]
Done 🎉

**Comment by gtd** [comment]
@lazyatom Don't have time to do so now but I'll roll a release when I get a chance...

**Comment by lazyatom** [comment]
> @lazyatom Don't have time to do so now but I'll roll a release when I get a chance...

Or add me as a collaborator/maintainer 😉

**Pull request merged**
